language: node_js

branches:
  only:
  - development

before_install:
- npm install -g harp

install:
- npm install

before_script:
- git config --global user.name 'Travis CI'
- git config --global user.email 'user@example.com'
- echo 'runnnnn'
- ls -a

script:
- cd ./public
- harp compile
- pwd

after_success:
- chmod +x ../build.sh
- ../build.sh